name: pre-release

on:
  push:
    branches:
      - "master"
      - "ci"

jobs:
  release:
    name: pre-release
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: target/release/task
