name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: release
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: softprops/action-gh-release@v1
        with:
          files: target/release/task
