on: [push]

name: rust

jobs:
  test:
    name: Test and coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-llvm-cov
          version: latest
          use-tool-cache: true
      - uses: actions-rs/install@v0.1
        with:
          crate: nextest
          version: latest
          use-tool-cache: true

      - name: Collect coverage data
        run: cargo llvm-cov nextest
