on: [push]

name: rust

jobs:
  test:
    name: Test and coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      - name: Debug
        run: ls -al

      - name: Collect coverage data
        run: cargo llvm-cov nextest
